version: 0.2

phases:
  build:
    commands:
      # install homebrew
      - NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /root/.bashrc
      - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - brew --version

      # install aws-vault
      - brew install aws-vault

      # install terraform
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/terraform
      - terraform --version
      # assume integration account role
      - echo "Before assuming role $ROLE_ARN"
      - bash ./scripts/assume_role.sh arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server this_profile
      - cd api
      - echo "After assuming role $ROLE_ARN"
      - terraform init --backend-config=backend_ecaas_api_integration.hcl
      - terraform plan

  post_build:
    commands:
