version: 0.2

phases:
  build:
    commands:
      - bash ./scripts/assume_role.sh arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server ci_server
      - export AWS_PROFILE=ci_server

      - find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      - aws lambda create-function --function-name hem-lambda --runtime provided.al2023 --role arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server --handler rust.handler --zip-file fileb://bootstrap.zip

  post_build:
    commands:
      - echo "Running post_build commands"