version: 0.2

phases:
  build:
    commands:
      - bash ./scripts/assume_role.sh arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server ci_server
      - export AWS_PROFILE=ci_server

      - ls -R $CODEBUILD_SRC_DIR_build_hem_lambda_output
      - aws lambda create-function --function-name hem-lambda --runtime provided.al2023 --role arn:aws:iam::$AWS_ACCOUNT_ID:role/ci-server --handler rust.handler --zip-file fileb://$CODEBUILD_SRC_DIR_build_hem_lambda_output/bootstrap.zip

  post_build:
    commands:
      - echo "Running post_build commands"