version: 0.2

phases:
  build:
    commands:
      # navigate to directory for hem source code
      - cd $CODEBUILD_SRC_DIR_build_hem_lambda_output

      # install rust and cargo
      # -y option to accept default configuration
      - curl https://sh.rustup.rs -sSf | sh -s -- -y

      # configure shell so we can use "cargo" command
      - . "$HOME/.cargo/env"

      - pip3 install cargo-lambda

      - cd hem-lambda
      - cargo lambda deploy hem-lambda

  post_build:
    commands:
      - echo "Running post_build commands"