version: 0.2

phases:
  install:
    runtime-versions:
      rust: latest
    commands:
      - rustup update stable
      - rustup default stable
      - rustc --version
  build:
    commands:
      # configure shell so we can use "cargo" command
      - . "$HOME/.cargo/env"

      # enter directory for lambda, make hem & fhs sources available
      - cd lambda
      - ln -sf $CODEBUILD_SRC_DIR_hem_core_source_output hem
      - ln -sf $CODEBUILD_SRC_DIR_fhs_wrapper_source_output fhs

      # run hem core tests
      - cd hem
      - cargo test --lib
      - cargo test --test e2e -- --nocapture

      # run fhs wrapper tests
      - cd ../fhs
      - cargo test --lib

cache:
  paths:
    - '/root/.cargo/registry/**/*'