openapi: "3.1.0"
info:
  title: Energy Calculation as a Service
  version: "1.0"
servers:
  - url: https://api.server.test/v1
security: []
paths:
  /api:
    get:
      operationId: ApiMetadata
      summary: Get information about the ECaaS API
      responses:
        "200":
          description: OK
  /future-homes-standard-compliance:
    post:
      operationId: FHSCompliance
      summary: Check Future Homes Standard (FHS) compliance.
      description: "Check compliance with the Future Homes Standard (FHS) based on the energy performance of a building calculated using the Home Energy Model (HEM)."
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: object
                  $ref: "./fhs_input.schema.json"
      responses:
        "200":
          description: "A summary of a successful HEM calculation to determine compliance with the Future Homes Standard (FHS)."
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                  - meta
                properties:
                  data:
                    $ref: "#/components/schemas/FhsComplianceResponse"
                  meta:
                    $ref: "#/components/schemas/FhsMeta"
              example:
                $ref: "./example_response.json"
        "422":
          description: "An error denoting that the request could not be processed by the calculator."
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - errors
                properties:
                  errors:
                    $ref: "#/components/schemas/JsonApiOnePointOneErrors"

components:
  schemas:
    FhsComplianceResponse:
      type: object
      properties:
        dwelling_emission_rate:
          type: number
          description: "The calculated DER (Dwelling Emission Rate) of the building. Unit: kgCO₂e/m²."
        target_emission_rate:
          type: number
          description: "The determined TER (Target Emission Rate) used for the calculation for this building. Unit: kgCO₂e/m²."
        emission_rate_compliant:
          type: boolean
          description: "Whether this calculation determines that the building with the provided properties complies with the Future Homes Standard for emission rate."
        dwelling_primary_energy_rate:
          type: number
          description: "The calculated DPER (Dwelling Primary Energy Rate) of the building. Unit: kWh/m²."
        target_primary_energy_rate:
          type: number
          description: "The determined TPER (Target Primary Energy Rate) used for the calculation for this building. Unit: kWh/m²."
        primary_energy_rate_compliant:
          type: boolean
          description: "Whether the calculated Dwelling Primary Energy Rate is compliant with FHS."
        dwelling_fabric_energy_efficiency:
          type: number
          description: "The calculated DFEE (Dwelling Fabric Energy Efficiency) of the building. Unit: kWh/m².yr."
        target_fabric_energy_efficiency:
          type: number
          description: "The determined TPEE (Target Fabric Energy Efficiency) of the building. Unit: kWh/m².yr."
        fabric_energy_efficient_compliant:
          type: boolean
          description: "Whether the calculated Dwelling Fabric Energy Efficiency is compliant with FHS."
        energy_demand:
          $ref: "#/components/schemas/FhsEnergyDemand"
        delivered_energy_use:
          $ref: "#/components/schemas/FhsDeliveredEnergyUse"
        energy_use_by_fuel:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/FhsEnergyPerformanceValue"

    FhsEnergyDemand:
      type: object
      properties:
        space_heating:
          $ref: "#/components/schemas/FhsEnergyPerformanceValue"
        space_cooling:
          $ref: "#/components/schemas/FhsEnergyPerformanceValue"

    FhsDeliveredEnergyUse:
      type: object
      properties:
        total:
          $ref: "#/components/schemas/FhsEnergyPerformanceValue"
        by_system:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/FhsEnergyPerformanceValue"

    FhsEnergyPerformanceValue:
      type: object
      properties:
        actual:
          type: number
          description: "The actual measured energy performance for a particular metric. Unit: kWh/m²."
        notional:
          type: number
          description: "The notional energy performance for a particular metric. Unit: kWh/m²."

    FhsMeta:
      type: object
      properties:
        hem_version:
          type: string
          description: "An identifier representing which version of HEM (the specification) was used, or available to be used, in this calculation."
          example: "0.32"
        hem_version_date:
          type: string
          description: "The date when the version of the HEM specification being used was published. Format: YYYY-MM-DD."
          format: date
          example: "2025-02-15"
        fhs_version:
          type: string
          description: "An identifier representing which version of FHS (Future Homes Standard) (the specification) was used, or available to be used, in this calculation."
          example: "0.23"
        fhs_version_date:
          type: string
          description: "The date when the version of the FHS specification being used was published. Format: YYYY-MM-DD."
          format: date
        software_version:
          type: string
          description: "A unique identifier, usually a SHA, for the version of the HEM software library being used for this calculation."
          example: "521c68bd9c715f82205d7d1afd7b88d038839d26"

    # following is a port of the latest-best version of the errors definition for JSON API 1.1 as from: https://github.com/json-api/json-api/pull/1603/files#diff-a917ba3b0d912319f14b934e128bf0425ca1b7c989630f006689c845c5e1ab7d
    JsonApiOnePointOneErrors:
      type: array
      items:
        $ref: "#/components/schemas/JsonApiOnePointOneError"
      uniqueItems: true

    JsonApiOnePointOneError:
      type: object
      anyOf:
        - required:
            - id
        - required:
            - links
        - required:
            - status
        - required:
            - code
        - required:
            - title
        - required:
            - detail
        - required:
            - source
        - required:
            - meta
      properties:
        id:
          description: "A unique identifier for this particular occurrence of the problem."
          type: string
        links:
          $ref: "#/components/schemas/JsonApiOnePointOneErrorLinks"
        status:
          description: "The HTTP status code applicable to this problem, expressed as a string value."
          type: string
        code:
          description: "An application-specific error code, expressed as a string value."
          type: string
        title:
          description: "A short, human-readable summary of the problem. It **SHOULD NOT** change from occurrence to occurrence of the problem, except for purposes of localization."
          type: string
        detail:
          description: "A human-readable explanation specific to this occurrence of the problem."
          type: string
        source:
          $ref: "#/components/schemas/JsonApiOnePointOneErrorSource"
        meta:
          $ref: "#/components/schemas/JsonApiOnePointOneMeta"
      unevaluatedProperties: false

    JsonApiOnePointOneErrorLinks:
      description: "The error links object **MAY** contain the following members: about."
      type: object
      allOf:
        - $ref: "#/components/schemas/JsonApiOnePointOneLinks"
      anyOf:
        - $ref: "#/components/schemas/JsonApiOnePointOneAtMemberName"
      properties:
        about:
          description: "A link that leads to further details about this particular occurrence of the problem."
          $ref: "#/components/schemas/JsonApiOnePointOneLink"
        type:
          description: "A link that identifies the type of error that this particular error is an instance of."
          $ref: "#/components/schemas/JsonApiOnePointOneLink"

    JsonApiOnePointOneErrorSource:
      type: object
      properties:
        pointer:
          description: 'A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].'
          type: string
          pattern: "^(?:\\/(?:[^~/]|~0|~1)*)*$"
        parameter:
          description: "A string indicating which query parameter caused the error."
          type: string
        header:
          description: "A string indicating the name of a single request header which caused the error."
          type: string

    JsonApiOnePointOneLinkObject:
      type: object
      required:
        - href
      properties:
        href:
          $ref: "#/components/schemas/JsonApiOnePointOneLinkUrl"
        meta:
          $ref: "#/components/schemas/JsonApiOnePointOneMeta"
        rel:
          type: string
        title:
          type: string
        type:
          type: string
        hreflang:
          type: string
        describedby:
          $ref: "#/components/schemas/JsonApiOnePointOneLink"

    JsonApiOnePointOneLinkUrl:
      description: "A string containing the link's URL."
      type: string
      format: uri
      $comment: "URI regex as per https://tools.ietf.org/html/rfc3986#appendix-B"
      pattern: "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?"

    JsonApiOnePointOneLink:
      description: "A link **MUST** be represented as either: a string containing the link's URL or a link object."
      oneOf:
        - $ref: "#/components/schemas/JsonApiOnePointOneLinkUrl"
        - $ref: "#/components/schemas/JsonApiOnePointOneLinkObject"

    JsonApiOnePointOneLinks:
      type: object

    JsonApiOnePointOneMeta:
      description: "Nonstandard meta-information that can not be represented as an attribute or relationship."
      type: object
      anyOf:
        - $ref: "#/components/schemas/JsonApiOnePointOneMemberName"
        - $ref: "#/components/schemas/JsonApiOnePointOneAtMemberName"
      unevaluatedProperties: false

    JsonApiOnePointOneAtMemberName:
      description: "@member name may contain any valid JSON value."
      type: object
      patternProperties:
        "^@[a-zA-Z0-9]{1}(?:[-\\w]*[a-zA-Z0-9])?$": true

    JsonApiOnePointOneMemberName:
      description: "Member name may contain any valid JSON value."
      type: object
      patternProperties:
        "^[a-zA-Z0-9]{1}(?:[-\\w]*[a-zA-Z0-9])?$": true
